### ISSUE TITLE
Solve setup.py issue

### ISSUE THREAD

**Issue by rohithasrk** [IMGIITRoorkee/django-filemanager#44]
There seems to be issue in installing some package when running `python setup.py develop`. The goal is to fix it.

**Comment by fakabbir** [comment]
I tried `python setup.py install` and `python setup.py develop`. Their was no issue with my system. 
Perhaps, your system is not configured well. 
Can you share your output/log. 

Output File/Log File : https://gist.github.com/anonymous/7773adbb06df820085a78399e1897f59

**Comment by rohithasrk** [comment]
```
running develop
running egg_info
writing requirements to django_filemanager.egg-info/requires.txt
writing django_filemanager.egg-info/PKG-INFO
writing top-level names to django_filemanager.egg-info/top_level.txt
writing dependency_links to django_filemanager.egg-info/dependency_links.txt
reading manifest file 'django_filemanager.egg-info/SOURCES.txt'
writing manifest file 'django_filemanager.egg-info/SOURCES.txt'
running build_ext
Creating /home/rohith/Documents/img/venv/lib/python2.7/site-packages/django-filemanager.egg-link (link to .)
Adding django-filemanager 0.0.1 to easy-install.pth file

Installed /home/rohith/Documents/img/django-filemanager
Processing dependencies for django-filemanager==0.0.1
Searching for Pillow
Reading https://pypi.python.org/simple/Pillow/
Downloading https://pypi.python.org/packages/e0/82/ec499c78bfe4ecaa91c2f3000040451d187ed0a816d58b8543e29c48827f/Pillow-4.3.0.tar.gz#md5=ac8904e17922c8a699ff7d6cb0cf89cd
Best match: Pillow 4.3.0
Processing Pillow-4.3.0.tar.gz
Writing /tmp/easy_install-CqPqCX/Pillow-4.3.0/setup.cfg
Running Pillow-4.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CqPqCX/Pillow-4.3.0/egg-dist-tmp-Mm3sKr
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching 'codecov.yml'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching '.travis'
warning: no previously-included files found matching '.travis/*'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Building using 4 processes
Building using 4 processes
Building using 4 processes
Building using 4 processes
Building using 4 processes
Building using 4 processes
Building using 4 processes
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 4.3.0
platform     linux2 2.7.6 (default, Oct 26 2016, 20:30:19)
             [GCC 4.8.4]
--------------------------------------------------------------------
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
*** RAQM support not available
--- LITTLECMS2 support available
--- WEBP support available
--- WEBPMUX support available
--------------------------------------------------------------------
To add a missing option, make sure you have the required
library and headers.
See https://pillow.readthedocs.io/en/latest/installation.html#building-from-source

To check the build, run the selftest.py script.

Moving Pillow-4.3.0-py2.7-linux-x86_64.egg to /home/rohith/Documents/img/venv/lib/python2.7/site-packages
Adding Pillow 4.3.0 to easy-install.pth file
Installing pildriver.py script to /home/rohith/Documents/img/venv/bin
Installing viewer.py script to /home/rohith/Documents/img/venv/bin
Installing gifmaker.py script to /home/rohith/Documents/img/venv/bin
Installing pilconvert.py script to /home/rohith/Documents/img/venv/bin
Installing pilfont.py script to /home/rohith/Documents/img/venv/bin
Installing pilfile.py script to /home/rohith/Documents/img/venv/bin
Installing explode.py script to /home/rohith/Documents/img/venv/bin
Installing pilprint.py script to /home/rohith/Documents/img/venv/bin
Installing player.py script to /home/rohith/Documents/img/venv/bin
Installing thresholder.py script to /home/rohith/Documents/img/venv/bin
Installing painter.py script to /home/rohith/Documents/img/venv/bin
Installing enhancer.py script to /home/rohith/Documents/img/venv/bin

Installed /home/rohith/Documents/img/venv/lib/python2.7/site-packages/Pillow-4.3.0-py2.7-linux-x86_64.egg
Searching for django<1.8,>=1.7
Reading https://pypi.python.org/simple/django/
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 357, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable

Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
Downloading https://pypi.python.org/packages/53/2a/cca393c0d65813f9f8e4d41e4a4d7d64fe8a6bd6dd7276583e2b6653af61/Django-1.7.11.tar.gz#md5=030b2f9c99a6e4e0418eadf7dba9e235
Best match: Django 1.7.11
Processing Django-1.7.11.tar.gz
Writing /tmp/easy_install-S6VeK8/Django-1.7.11/setup.cfg
Running Django-1.7.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-S6VeK8/Django-1.7.11/egg-dist-tmp-LZW5Sx
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
creating /home/rohith/Documents/img/venv/lib/python2.7/site-packages/Django-1.7.11-py2.7.egg
Extracting Django-1.7.11-py2.7.egg to /home/rohith/Documents/img/venv/lib/python2.7/site-packages
Adding Django 1.7.11 to easy-install.pth file
Installing django-admin.py script to /home/rohith/Documents/img/venv/bin
Installing django-admin script to /home/rohith/Documents/img/venv/bin

Installed /home/rohith/Documents/img/venv/lib/python2.7/site-packages/Django-1.7.11-py2.7.egg
Searching for olefile
Reading https://pypi.python.org/simple/olefile/
Downloading https://pypi.python.org/packages/35/17/c15d41d5a8f8b98cc3df25eb00c5cee76193114c78e5674df6ef4ac92647/olefile-0.44.zip#md5=fc625554e4e7f0c2ddcd00baa3c74ff5
Best match: olefile 0.44
Processing olefile-0.44.zip
Writing /tmp/easy_install-QIErdE/olefile-0.44/setup.cfg
Running olefile-0.44/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QIErdE/olefile-0.44/egg-dist-tmp-8GDhfQ
zip_safe flag not set; analyzing archive contents...
Moving olefile-0.44-py2.7.egg to /home/rohith/Documents/img/venv/lib/python2.7/site-packages
Adding olefile 0.44 to easy-install.pth file

Installed /home/rohith/Documents/img/venv/lib/python2.7/site-packages/olefile-0.44-py2.7.egg
Finished processing dependencies for django-filemanager==0.0.1

```

**Comment by shaddygarg** [comment]
@rohithasrk I think that this issue can be closed.

**Comment by rohithasrk** [comment]
@shaddygarg Not able to replicate it anymore?

**Comment by fakabbir** [comment]
@shaddygarg Any specific reason for **I think**
